name: Deploy Frontend to Azure

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy frontend to Azure VM
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            set -e
            cd /opt/idea1thon/FE
            git fetch origin dev
            git reset --hard origin/dev
            npm ci
            npm run build
